### ISSUE TITLE
[Bug]: MtToast is partially hidden on small screen sizes

### ISSUE THREAD

**Issue by dieudtq** [shopware/meteor#184]
### Package

@meteor/component-library

### Package version

3.6.0

### Link to minimal reproduction

https://meteor-component-library.vercel.app/?path=/story/components-feedback-indicator-mt-toast--default

### Steps to reproduce

Show a toast in small screen width < 1024px

### Actual behavior

Toast is partially hidden in small screen resolution. The right part is hidden, and the Toast can not be closed.
Happen on both StoryBook and real project:

![image](https://github.com/shopware/meteor/assets/45735885/a9c809cb-62c0-4209-9d51-be043039e9a9)

### Expected behavior

Toast display fully in small screen resolution entirely

### Code of Conduct

- [X] I have read and agree to follow Meteor's [Code of Conduct](https://github.com/shopware/meteor/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haberkamp** [comment]
I've written a fix (#211) for the issue. It will be out in the next release.
