### ISSUE TITLE
[Bug]: The tag deletion is not working on the Safari browser

### ISSUE THREAD

**Issue by sydinh** [shopware/meteor#199]
### Package

@meteor/component-library

### Package version

3.8.0

### Link to minimal reproduction

https://meteor-component-library.vercel.app/?path=/docs/components-form-mt-select--docs

### Steps to reproduce

1. Open the link on the Safari browser

2. Set the property "enableMultiSelection" to TRUE

3. Select more tags and try to delete one

### Actual behavior

Not able to delete tags

### Expected behavior

Tags should be deleted

### Code of Conduct

- [X] I have read and agree to follow Meteor's [Code of Conduct](https://github.com/shopware/meteor/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haberkamp** [comment]
The linked PR is merged, I'll close this issue. Thank you @sydinh
