### ISSUE TITLE
[Feature]: meteor-component-library css bundle is huge due to fonts

### ISSUE THREAD

**Issue by cyl3x** [shopware/meteor#279]
### Package

@meteor/component-library

### Package version

3.11.0

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-xmwwbk?file=src%2Fmain.js

### Steps to reproduce

- Create a vue + vite project
- Install the meteor-component-library
- Add a `import '@shopware-ag/meteor-component-library/dist/style.css';`
- Build the app

### Actual behavior

The resulting css file is about ~4.5MB (~3.5MB gzipped) according to vite. Removing the inlined fonts will reduce the css bundle down to ~180KB (~25KB gzipped).

### Expected behavior

Fonts aren't inlined as base64 within the same css file, but bundled separately to allow more selective import. Bundling 10 different fonts feels clumsy, and I'd like to be able to bundle, say, regular fonts only when I don't have bold or italic text.

### Code of Conduct

- [X] I have read and agree to follow Meteor's [Code of Conduct](https://github.com/shopware/meteor/blob/main/CODE_OF_CONDUCT.md)

**Comment by shyim** [comment]
the attached PR is not merged, open it up again?

**Comment by bojanrajh** [comment]
There's [another PR](https://github.com/shopware/meteor/pull/365) that was merged, but is not released yet.
