### ISSUE TITLE
[Bug]: Component library fails with Nuxt 3

### ISSUE THREAD

**Issue by atloss** [shopware/meteor#91]
### Package

@meteor/component-library

### Package version

3.0.0-alpha1

### Link to minimal reproduction

https://stackblitz.com/edit/meteor-component-libary-nuxt-3?file=app.vue

### Steps to reproduce

1. Setup a running Nuxt 3 project with `npx nuxi@latest init <project-name>`
2. Add the meteor component library `npm i @shopware-ag/meteor-component-library`
3. Import the styles
4. Try using the `<SwCard>` component

### Actual behavior

The app crashes with a 500 error: `HTMLElement is not defined`

### Expected behavior

The package also works for Nuxt 3 since Vue 3 is the underlying framework. This was also the case for v2.

### Code of Conduct

- [X] I have read and agree to follow Meteor's [Code of Conduct](https://github.com/shopware/meteor/blob/main/CODE_OF_CONDUCT.md)

**Comment by jleifeld** [comment]
Thanks for raising up this issue. I will have a look at it 👀
